### ISSUE TITLE
Failed to load `Label` as custom class in XIB file

### ISSUE THREAD

**Issue by jjorn** [JamitLabs/JamitFoundation#35]
<img width="368" alt="Screen Shot 2020-10-14 at 08 46 23" src="https://user-images.githubusercontent.com/43874281/95953280-ebdbcb00-0df9-11eb-96b0-40fc1e3a386c.png">

**Comment by mrylmz** [comment]
Wasn't possible for me to reproduce the issue with the current version. If you will notice it again please feel free to reopen the issue and add some description on Xcode version and supported iOS versions.
